# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Symfony

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
    #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
    # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
    # uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.3'
    - uses: actions/checkout@v3
    - name: Copy .env.test.local
      run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
#    - name: Create Database
#      run: |
#        mkdir -p $GITHUB_WORKSPACE/data
#        touch $GITHUB_WORKSPACE/data/database.sqlite
#    - name: List workspace contents
#      run: |
#        ls -l $GITHUB_WORKSPACE
#        ls -l $GITHUB_WORKSPACE/data
    - name: Load .env file
      run: source .env

    - name: Debug DATABASE_URL
      run: echo $DATABASE_URL
    - name: Config Database
      env:
        DATABASE_URL: "sqlite:///$GITHUB_WORKSPACE/data/database.sqlite"
      run: |
        php bin/console doctrine:database:create --env=test
        php bin/console doctrine:schema:update --env=test --force
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
    - name: Check Twig Templates
      run: php bin/console lint:twig src
    - name: Check YAML Files
      run: php bin/console lint:yaml templates
    - name: Check XLIFF Files
      run: php bin/console lint:xliff translations
