name: Symfony Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '8.1'
          extensions: pdo,mysqli,intl

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: php bin/phpunit

      - name: Upload test results (optional)
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: ./build/phpunit.xml